name: dart_services
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  serinus: ^1.0.3
  serinus_config: ^1.0.6
  dartpad_shared:
    path: ../dartpad_shared
  analysis_server_lib: ^0.2.5
  analyzer: ^7.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
